import { useEffect } from 'react';
import Footer from '../components/Footer';
import { Shield, Lock, Globe, CheckCircle } from 'lucide-react';
import { motion } from 'framer-motion';

export default function PrivacyPage() {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    const containerVariants = {
        hidden: { opacity: 0 },
        visible: {
            opacity: 1,
            transition: { staggerChildren: 0.1 }
        }
    };

    const itemVariants = {
        hidden: { opacity: 0, y: 20 },
        visible: { opacity: 1, y: 0, transition: { duration: 0.8 } }
    };

    return (
        <div className="min-h-screen bg-neutral-50 flex flex-col font-sans">
            {/* Hero Section */}
            <div className="pt-32 pb-20 px-6 max-w-4xl mx-auto text-center">
                <motion.div initial="hidden" animate="visible" variants={containerVariants}>
                    <motion.p variants={itemVariants} className="text-[10px] font-sans tracking-[0.3em] uppercase text-ruby-red mb-4">
                        Legal Information
                    </motion.p>
                    <motion.h1 variants={itemVariants} className="font-serif text-4xl lg:text-5xl text-dark-red mb-6 leading-tight">
                        Privacy Policy
                    </motion.h1>
                    <motion.p variants={itemVariants} className="font-sans text-gray-600 text-base leading-relaxed max-w-2xl mx-auto">
                        Welcome to Bodilicious. We are committed to protecting your privacy and ensuring you have a seamless, secure experience on our luxury skincare platform. By using our website, you agree to the practices described below.
                    </motion.p>
                </motion.div>
            </div>

            {/* Content Section */}
            <div className="flex-1 max-w-3xl mx-auto w-full px-6 pb-24 space-y-12">
                <div className="pb-6 border-b border-silk mb-8">
                    <div className="flex items-center gap-3 mb-2">
                        <Shield className="text-ruby-red" size={24} />
                        <h2 className="font-serif text-3xl text-dark-red">Privacy Policy</h2>
                    </div>
                    <p className="text-sm text-gray-500 font-sans tracking-wide">How we protect and manage your data.</p>
                </div>

                <div className="space-y-10">
                    <section className="bg-white p-8 border border-silk shadow-sm rounded-sm hover:border-ruby-red/30 transition-colors">
                        <h3 className="font-serif text-xl text-dark-red mb-4 flex items-center gap-2">
                            <Lock size={18} className="text-grey-beige" /> Data We Collect
                        </h3>
                        <div className="space-y-4 text-sm text-gray-600 leading-relaxed font-light">
                            <p><strong>Personal Data:</strong> Information about an individual who can be identified from those data, including Email, First/Last name, Phone number, and Address details.</p>
                            <p><strong>Usage Data:</strong> Data collected automatically generated by the use of the Service (e.g., duration of a page visit, IP address, browser type).</p>
                            <p><strong>Cookies:</strong> Small pieces of data stored on your device used to track activity on our Website and hold certain information.</p>
                        </div>
                    </section>

                    <section className="bg-white p-8 border border-silk shadow-sm rounded-sm hover:border-ruby-red/30 transition-colors">
                        <h3 className="font-serif text-xl text-dark-red mb-4 flex items-center gap-2">
                            <CheckCircle size={18} className="text-grey-beige" /> How We Use It
                        </h3>
                        <ul className="space-y-3 text-sm text-gray-600 leading-relaxed font-light list-none">
                            <li className="flex gap-3"><span className="text-ruby-red mt-1">•</span> To provide and maintain our Website</li>
                            <li className="flex gap-3"><span className="text-ruby-red mt-1">•</span> To notify you about changes</li>
                            <li className="flex gap-3"><span className="text-ruby-red mt-1">•</span> To provide customer support</li>
                            <li className="flex gap-3"><span className="text-ruby-red mt-1">•</span> To gather analysis to improve our Website</li>
                            <li className="flex gap-3"><span className="text-ruby-red mt-1">•</span> To monitor usage and detect technical issues</li>
                        </ul>
                    </section>

                    <section className="bg-white p-8 border border-silk shadow-sm rounded-sm hover:border-ruby-red/30 transition-colors">
                        <h3 className="font-serif text-xl text-dark-red mb-4 flex items-center gap-2">
                            <Globe size={18} className="text-grey-beige" /> Transfer & Disclosure
                        </h3>
                        <div className="space-y-4 text-sm text-gray-600 leading-relaxed font-light">
                            <p>Your information may be transferred to computers located outside of your jurisdiction. We take all necessary steps to ensure data is treated securely.</p>
                            <p>We do not sell, trade, or transfer to outside parties your personally identifiable information unless we provide advance notice. We may disclose your Personal Data in good faith to comply with legal obligations, protect Bodilicious' rights, or prevent wrongdoing.</p>
                        </div>
                    </section>
                </div>
            </div>

            <Footer />
        </div>
    );
}
